### Exploration et nettoyage

#### logements existants

In [2]:
import pandas as pd
import gdown

url = "https://drive.google.com/uc?id=1Y8lNwKN6KW2GgBOIzLRbDAYrj8pNs9kP"
output = "C:\\Users\\HP\\Desktop\\Master2\\ML\\m2_enedis_dpe_app\\data\\dpe_existant.csv"
gdown.download(url, output, quiet=False)

import pandas as pd
df_existant = pd.read_csv(output)

Downloading...
From (original): https://drive.google.com/uc?id=1Y8lNwKN6KW2GgBOIzLRbDAYrj8pNs9kP
From (redirected): https://drive.google.com/uc?id=1Y8lNwKN6KW2GgBOIzLRbDAYrj8pNs9kP&confirm=t&uuid=efdbe3de-41cc-4102-80e9-cd75ba49f7bf
To: C:\Users\HP\Desktop\Master2\ML\m2_enedis_dpe_app\data\dpe_existant.csv
100%|██████████| 126M/126M [00:04<00:00, 27.9MB/s]

In [3]:
pd.set_option('display.max_columns', None)
df_existant.head()

,code_departement_ban,conso_5_usages_ep,date_fin_validite_dpe,methode_application_dpe,code_region_ban,cout_total_5_usages,zone_climatique,hauteur_sous_plafond,emission_ges_chauffage,conso_chauffage_ep,nom_commune_ban,version_dpe,annee_construction,coordonnee_cartographique_x_ban,qualite_isolation_murs,type_batiment,conso_refroidissement_ep,periode_construction,type_energie_principale_chauffage,numero_dpe,qualite_isolation_menuiseries,conso_ecs_ep,date_reception_dpe,emission_ges_5_usages,inertie_lourde,isolation_toiture,etiquette_ges,modele_dpe,coordonnee_cartographique_y_ban,nombre_niveau_logement,code_postal_ban,surface_habitable_logement,etiquette_dpe,_score,presence_production_pv,type_installation_ecs,type_installation_chauffage,type_ventilation,surface_totale_capteurs_pv,typologie_logement
0,69.0,28727.8,2032-05-12,dpe maison individuelle,84.0,2693.3,H1c,2.5,7671.2,23676.5,Saint-Clément-de-Vers,2.1,1994.0,807850.62,moyenne,maison,0.0,1989-2000,Fioul domestique,2269E1049302M,moyenne,2343.4,2022-05-14,8507.0,0.0,1.0,E,DPE 3CL 2021 méthode logement,6570836.70,2.0,69790,133.6,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,69.0,47440.8,2032-01-16,dpe maison individuelle,84.0,2860.4,H1c,2.5,6136.6,40762.4,Propières,2.0,1947.0,811688.48,insuffisante,maison,0.0,avant 1948,Bois – Bûches,2269E0101374S,moyenne,5393.5,2022-01-18,6325.7,NaN,NaN,E,DPE 3CL 2021 méthode logement,6566988.16,2.0,69790,94.0,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,69.0,41945.9,2031-11-22,dpe maison individuelle,84.0,2619.4,H1c,2.4,1286.4,38650.0,Saint-Bonnet-des-Bruyères,1.1,1947.0,815715.28,insuffisante,maison,0.0,avant 1948,Électricité,2169E0761678Z,insuffisante,3081.5,2021-11-24,1379.9,NaN,NaN,C,DPE 3CL 2021 méthode logement,6575160.49,1.0,69790,50.1,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,69.0,19626.9,2031-08-19,dpe maison individuelle,84.0,1743.0,H1c,2.9,517.7,15073.3,Saint-Bonnet-des-Bruyères,1.0,1947.0,814019.46,très bonne,maison,0.0,avant 1948,Électricité,2169E0199264R,très bonne,2108.1,2021-08-21,646.9,NaN,NaN,A,DPE 3CL 2021 méthode logement,6576616.26,1.0,69790,166.2,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69.0,56620.0,2031-11-28,dpe maison individuelle,84.0,5134.6,H1c,2.5,16260.5,50186.8,Propières,1.1,1947.0,812372.97,insuffisante,maison,0.0,avant 1948,Électricité,2169E0806561G,insuffisante,4992.9,2021-11-30,16442.9,NaN,NaN,G,DPE 3CL 2021 méthode logement,6567556.10,1.0,69790,134.2,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df_existant

,code_departement_ban,conso_5_usages_ep,date_fin_validite_dpe,methode_application_dpe,code_region_ban,cout_total_5_usages,zone_climatique,hauteur_sous_plafond,emission_ges_chauffage,conso_chauffage_ep,nom_commune_ban,version_dpe,annee_construction,coordonnee_cartographique_x_ban,qualite_isolation_murs,type_batiment,conso_refroidissement_ep,periode_construction,type_energie_principale_chauffage,numero_dpe,qualite_isolation_menuiseries,conso_ecs_ep,date_reception_dpe,emission_ges_5_usages,inertie_lourde,isolation_toiture,etiquette_ges,modele_dpe,coordonnee_cartographique_y_ban,nombre_niveau_logement,code_postal_ban,surface_habitable_logement,etiquette_dpe,_score,presence_production_pv,type_installation_ecs,type_installation_chauffage,type_ventilation,surface_totale_capteurs_pv,typologie_logement
0,69.0,28727.8,2032-05-12,dpe maison individuelle,84.0,2693.3,H1c,2.5,7671.2,23676.5,Saint-Clément-de-Vers,2.1,1994.0,807850.62,moyenne,maison,0.0,1989-2000,Fioul domestique,2269E1049302M,moyenne,2343.4,2022-05-14,8507.0,0.0,1.0,E,DPE 3CL 2021 méthode logement,6570836.70,2.0,69790,133.6,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,69.0,47440.8,2032-01-16,dpe maison individuelle,84.0,2860.4,H1c,2.5,6136.6,40762.4,Propières,2.0,1947.0,811688.48,insuffisante,maison,0.0,avant 1948,Bois – Bûches,2269E0101374S,moyenne,5393.5,2022-01-18,6325.7,NaN,NaN,E,DPE 3CL 2021 méthode logement,6566988.16,2.0,69790,94.0,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,69.0,41945.9,2031-11-22,dpe maison individuelle,84.0,2619.4,H1c,2.4,1286.4,38650.0,Saint-Bonnet-des-Bruyères,1.1,1947.0,815715.28,insuffisante,maison,0.0,avant 1948,Électricité,2169E0761678Z,insuffisante,3081.5,2021-11-24,1379.9,NaN,NaN,C,DPE 3CL 2021 méthode logement,6575160.49,1.0,69790,50.1,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,69.0,19626.9,2031-08-19,dpe maison individuelle,84.0,1743.0,H1c,2.9,517.7,15073.3,Saint-Bonnet-des-Bruyères,1.0,1947.0,814019.46,très bonne,maison,0.0,avant 1948,Électricité,2169E0199264R,très bonne,2108.1,2021-08-21,646.9,NaN,NaN,A,DPE 3CL 2021 méthode logement,6576616.26,1.0,69790,166.2,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69.0,56620.0,2031-11-28,dpe maison individuelle,84.0,5134.6,H1c,2.5,16260.5,50186.8,Propières,1.1,1947.0,812372.97,insuffisante,maison,0.0,avant 1948,Électricité,2169E0806561G,insuffisante,4992.9,2021-11-30,16442.9,NaN,NaN,G,DPE 3CL 2021 méthode logement,6567556.10,1.0,69790,134.2,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405179,69.0,14239.9,2035-09-17,dpe maison individuelle,84.0,1340.3,H1c,2.4,282.0,8209.8,Brindas,2.5,NaN,831743.19,moyenne,maison,113.5,avant 1948,Électricité,2569E2977923I,bonne,4375.0,2025-09-19,452.7,0.0,1.0,A,DPE 3CL 2021 méthode logement,6514825.95,3.0,69126,107.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405180,69.0,34202.2,2035-10-01,dpe maison individuelle,84.0,2772.2,H1c,2.5,912.3,27371.6,Brindas,2.5,NaN,831454.56,bonne,maison,46.1,1978-1982,Électricité,2569E3128511E,bonne,4833.3,2025-10-02,1105.9,0.0,1.0,B,DPE 3CL 2021 méthode logement,6514388.23,2.0,69126,150.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405181,69.0,31777.5,2035-09-28,dpe appartement individuel,84.0,2844.4,H1c,2.5,920.7,26805.5,Brindas,2.5,NaN,833462.45,insuffisante,appartement,0.0,avant 1948,Électricité,2569E3096531E,moyenne,4649.9,2025-09-30,1061.8,1.0,1.0,C,DPE 3CL 2021 méthode logement,6516389.16,1.0,69126,75.3,G,NaN,NaN,individuel,individuel,NaN,NaN,NaN
405182,69.0,3410.0,2032-12-27,dpe appartement individuel,84.0,306.0,H1c,2.5,234.7,1034.0,Brindas,2.2,2014.0,831539.77,très bonne,appartement,0.0,2013-2021,Gaz naturel,2269E3186083J,très bonne,1563.7,2022-12-29,612.6,1.0,0.0,C,DPE 3CL 2021 méthode logement,6514922.00,1.0,69126,44.6,C,NaN,NaN,collectif,collectif,NaN,NaN,NaN
405183,69.0,11435.4,2034-11-16,dpe maison individuelle,84.0,1329.4,H1c,2.5,1987.0,8753.4,Brindas,2.4,2018.0,831184.71,très bonne,maison,0.0,2013-2021,Gaz naturel,2469E4051070E,bonne,1568.4,2024-11-18,2374.8,0.0,1.0,C,DPE 3CL 2021 méthode logement,6514621.83,1.0,69126,82.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_existant['logement'] = "existant"

In [6]:
df_existant .head()

,code_departement_ban,conso_5_usages_ep,date_fin_validite_dpe,methode_application_dpe,code_region_ban,cout_total_5_usages,zone_climatique,hauteur_sous_plafond,emission_ges_chauffage,conso_chauffage_ep,nom_commune_ban,version_dpe,annee_construction,coordonnee_cartographique_x_ban,qualite_isolation_murs,type_batiment,conso_refroidissement_ep,periode_construction,type_energie_principale_chauffage,numero_dpe,qualite_isolation_menuiseries,conso_ecs_ep,date_reception_dpe,emission_ges_5_usages,inertie_lourde,isolation_toiture,etiquette_ges,modele_dpe,coordonnee_cartographique_y_ban,nombre_niveau_logement,code_postal_ban,surface_habitable_logement,etiquette_dpe,_score,presence_production_pv,type_installation_ecs,type_installation_chauffage,type_ventilation,surface_totale_capteurs_pv,typologie_logement,logement
0,69.0,28727.8,2032-05-12,dpe maison individuelle,84.0,2693.3,H1c,2.5,7671.2,23676.5,Saint-Clément-de-Vers,2.1,1994.0,807850.62,moyenne,maison,0.0,1989-2000,Fioul domestique,2269E1049302M,moyenne,2343.4,2022-05-14,8507.0,0.0,1.0,E,DPE 3CL 2021 méthode logement,6570836.70,2.0,69790,133.6,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,existant
1,69.0,47440.8,2032-01-16,dpe maison individuelle,84.0,2860.4,H1c,2.5,6136.6,40762.4,Propières,2.0,1947.0,811688.48,insuffisante,maison,0.0,avant 1948,Bois – Bûches,2269E0101374S,moyenne,5393.5,2022-01-18,6325.7,NaN,NaN,E,DPE 3CL 2021 méthode logement,6566988.16,2.0,69790,94.0,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,existant
2,69.0,41945.9,2031-11-22,dpe maison individuelle,84.0,2619.4,H1c,2.4,1286.4,38650.0,Saint-Bonnet-des-Bruyères,1.1,1947.0,815715.28,insuffisante,maison,0.0,avant 1948,Électricité,2169E0761678Z,insuffisante,3081.5,2021-11-24,1379.9,NaN,NaN,C,DPE 3CL 2021 méthode logement,6575160.49,1.0,69790,50.1,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN,existant
3,69.0,19626.9,2031-08-19,dpe maison individuelle,84.0,1743.0,H1c,2.9,517.7,15073.3,Saint-Bonnet-des-Bruyères,1.0,1947.0,814019.46,très bonne,maison,0.0,avant 1948,Électricité,2169E0199264R,très bonne,2108.1,2021-08-21,646.9,NaN,NaN,A,DPE 3CL 2021 méthode logement,6576616.26,1.0,69790,166.2,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,existant
4,69.0,56620.0,2031-11-28,dpe maison individuelle,84.0,5134.6,H1c,2.5,16260.5,50186.8,Propières,1.1,1947.0,812372.97,insuffisante,maison,0.0,avant 1948,Électricité,2169E0806561G,insuffisante,4992.9,2021-11-30,16442.9,NaN,NaN,G,DPE 3CL 2021 méthode logement,6567556.10,1.0,69790,134.2,G,NaN,1.0,NaN,NaN,NaN,NaN,NaN,existant

In [7]:
df_existant['periode_construction']

0          1989-2000
1         avant 1948
2         avant 1948
3         avant 1948
4         avant 1948
             ...
405179    avant 1948
405180     1978-1982
405181    avant 1948
405182     2013-2021
405183     2013-2021
Name: periode_construction, Length: 405184, dtype: object

#### importer le dataset adresse

In [8]:
url1 = "https://drive.google.com/uc?id=1wa54IQVYSvovnALxymwTI5rem456dB_f"
output = "C:\\Users\\HP\\Desktop\\Master2\\ML\\m2_enedis_dpe_app\\data\\adresse.csv"
gdown.download(url1, output, quiet=False)
adresse = pd.read_csv(output  , sep=";")

Downloading...
From: https://drive.google.com/uc?id=1wa54IQVYSvovnALxymwTI5rem456dB_f
To: C:\Users\HP\Desktop\Master2\ML\m2_enedis_dpe_app\data\adresse.csv
100%|██████████| 63.8M/63.8M [00:01<00:00, 36.5MB/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_21056\899731870.py:4: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  adresse = pd.read_csv(output  , sep=";")

In [9]:
adresse.head()

,id,id_fantoir,numero,rep,nom_voie,code_postal,code_insee,nom_commune,code_insee_ancienne_commune,nom_ancienne_commune,x,y,lon,lat,type_position,alias,nom_ld,libelle_acheminement,nom_afnor,source_position,source_nom_voie,certification_commune,cad_parcelles
0,69002_x415an_00003,NaN,3,NaN,Route de Matour,69790,69002,Aigueperse,NaN,NaN,810429.96,6576304.86,4.434187,46.277603,entrée,NaN,NaN,AIGUEPERSE,ROUTE DE MATOUR,commune,commune,1,NaN
1,69002_x415an_00111,NaN,111,NaN,Route de Matour,69790,69002,Aigueperse,NaN,NaN,810431.91,6576405.53,4.434236,46.278509,entrée,NaN,NaN,AIGUEPERSE,ROUTE DE MATOUR,commune,commune,1,NaN
2,69002_x415an_00165,NaN,165,NaN,Route de Matour,69790,69002,Aigueperse,NaN,NaN,810435.99,6576456.36,4.434301,46.278966,entrée,NaN,NaN,AIGUEPERSE,ROUTE DE MATOUR,commune,commune,1,NaN
3,69002_x415an_01148,NaN,1148,NaN,Route de Matour,69790,69002,Aigueperse,NaN,NaN,810670.70,6577363.19,4.437563,46.287092,entrée,NaN,NaN,AIGUEPERSE,ROUTE DE MATOUR,commune,commune,1,NaN
4,69002_wit9km_00007,NaN,7,NaN,Chemin des Dalhias,69790,69002,Aigueperse,NaN,NaN,811603.60,6576200.23,4.449401,46.276468,entrée,NaN,NaN,AIGUEPERSE,CHEMIN DES DALHIAS,commune,commune,1,NaN

In [10]:
print(df_existant[['coordonnee_cartographique_x_ban', 'coordonnee_cartographique_y_ban']])

        coordonnee_cartographique_x_ban  coordonnee_cartographique_y_ban
0                             807850.62                       6570836.70
1                             811688.48                       6566988.16
2                             815715.28                       6575160.49
3                             814019.46                       6576616.26
4                             812372.97                       6567556.10
...                                 ...                              ...
405179                        831743.19                       6514825.95
405180                        831454.56                       6514388.23
405181                        833462.45                       6516389.16
405182                        831539.77                       6514922.00
405183                        831184.71                       6514621.83

[405184 rows x 2 columns]

In [12]:
#afficher les colonnes avec des valeurs manquantes
df_existant.isnull().sum() * 100 / len(df_existant)

code_departement_ban                   0.109333
conso_5_usages_ep                      0.001974
date_fin_validite_dpe                  0.000000
methode_application_dpe                0.000000
code_region_ban                        0.109333
cout_total_5_usages                    0.002715
zone_climatique                        0.110814
hauteur_sous_plafond                   0.000000
emission_ges_chauffage                 0.001481
conso_chauffage_ep                     0.001481
nom_commune_ban                        0.000000
version_dpe                            0.000000
annee_construction                    42.370380
coordonnee_cartographique_x_ban        0.000000
qualite_isolation_murs                 0.006417
type_batiment                          0.000000
conso_refroidissement_ep               0.000000
periode_construction                   0.000000
type_energie_principale_chauffage      0.000000
numero_dpe                             0.000000
qualite_isolation_menuiseries          0.000000
conso_ecs_ep                           0.000000
date_reception_dpe                     0.000000
emission_ges_5_usages                  0.001974
inertie_lourde                        39.097299
isolation_toiture                     38.601228
etiquette_ges                          0.000000
modele_dpe                             0.000000
coordonnee_cartographique_y_ban        0.000000
nombre_niveau_logement                 2.203443
code_postal_ban                        0.000000
surface_habitable_logement             2.071651
etiquette_dpe                          0.000000
_score                               100.000000
presence_production_pv                95.516111
type_installation_ecs                 11.289192
type_installation_chauffage           11.289192
type_ventilation                      96.835265
surface_totale_capteurs_pv            98.972566
typologie_logement                    99.113983
logement                               0.000000
dtype: float64

#### nettoyage

In [13]:
#garder les colonnes avec mmoins de 95% de valeurs manquantes
valeur_ratio = df_existant.isna().mean() * 100
df_existant = df_existant.loc[:, valeur_ratio < 95]  # garde les colonnes avec <95% de NaN

In [14]:
#remplacer les valeurs manquantes par la moyenne de la colonne
for col in df_existant.select_dtypes(include=['float64', 'int64']).columns:
    df_existant[col].fillna(df_existant[col].mean(), inplace=True)

#remplacer les valeurs manquantes par la valeur la plus fréquente de la colonne
for col in df_existant.select_dtypes(include=['object']).columns:
    df_existant[col].fillna(df_existant[col].mode()[0], inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_21056\2006098360.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_existant[col].fillna(df_existant[col].mean(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_21056\2006098360.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_existant[col].fillna(df_existant[col].mean(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_21056\2006098360.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_existant[col].fillna(df_existant[col].mode()[0], inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_21056\2006098360.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_existant[col].fillna(df_existant[col].mode()[0], inplace=True)

In [15]:
df_existant.isnull().sum() * 100 / len(df_existant)

code_departement_ban                 0.0
conso_5_usages_ep                    0.0
date_fin_validite_dpe                0.0
methode_application_dpe              0.0
code_region_ban                      0.0
cout_total_5_usages                  0.0
zone_climatique                      0.0
hauteur_sous_plafond                 0.0
emission_ges_chauffage               0.0
conso_chauffage_ep                   0.0
nom_commune_ban                      0.0
version_dpe                          0.0
annee_construction                   0.0
coordonnee_cartographique_x_ban      0.0
qualite_isolation_murs               0.0
type_batiment                        0.0
conso_refroidissement_ep             0.0
periode_construction                 0.0
type_energie_principale_chauffage    0.0
numero_dpe                           0.0
qualite_isolation_menuiseries        0.0
conso_ecs_ep                         0.0
date_reception_dpe                   0.0
emission_ges_5_usages                0.0
inertie_lourde                       0.0
isolation_toiture                    0.0
etiquette_ges                        0.0
modele_dpe                           0.0
coordonnee_cartographique_y_ban      0.0
nombre_niveau_logement               0.0
code_postal_ban                      0.0
surface_habitable_logement           0.0
etiquette_dpe                        0.0
type_installation_ecs                0.0
type_installation_chauffage          0.0
logement                             0.0
dtype: float64